services:
  clans:
    image: ghcr.io/zephyrcodesstuff/clans:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - RUST_LOG=${LOG_LEVEL:-info}
      - MONGO_URI=mongodb://mongo:27017/clans
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    ports:
      - "8080:8080"
    networks:
      - clans
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - clans
    volumes:
      - clans-data:/data/db
  
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "443:443"
      - "80:80"
    networks:
      - clans
    depends_on:
      - clans
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

      # NOTE: change this to a directory containing your `privkey.pem` and `fullchain.pem`.
      #       Not doing this will panic the container on startup.
      #
      #       Also, change the `server_name` in the `nginx.conf` to your domain.
      - ./certs:/etc/nginx/certs:ro

volumes:
  clans-data:

networks:
  clans:
    name: clans-network
